/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tree.gltf --transform
Author: Epic_Tree_Store (https://sketchfab.com/johngreenstone)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tree-c25e5fc2bfa54d24a165a8a207c0a6d7
Title: Tree
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/tree-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.66, -1.17, 0.16]} rotation={[1.4, -1.57, -Math.PI]}>
        <group position={[-1.15, -7.65, -1.22]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.raw2} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.raw2} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.raw2} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tree-transformed.glb')
